# Generated by Django 3.1 on 2021-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_and_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feuture',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
