# Generated by Django 3.1 on 2021-01-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_and_list', '0002_product_feuture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='name_lat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
